### ISSUE TITLE
remote sync not loaded

### ISSUE THREAD

**Issue by Donatomar** [yongkangchen/remote-sync#397]
Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

remote-sync 4.1.5

binding@unknown – Cannot find module '/Users/donato/.atom/packages/remote-sync/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/donato/.atom/packages/remote-sync/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/donato/.atom/packages/remote-sync/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/donato/.atom/packages/remote-sync/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/donato/.atom/packages/remote-sync/node_modules/fsevents/lib/binding'

**Comment by electricarts** [comment]
Same here. Remote-sync doesn't load. Atom 1.17.0 - Mac

**Comment by haugli92** [comment]
+1

**Comment by zaramme** [comment]
It seemed be happen on my Atom, too.
I fixed issue #388 by edit `context.cson` and context menu has appeared again.
But remote sync functions seemed be not working yet.  
on Atom 1.17.0, Mac.

**Comment by supremacy2k** [comment]
By manually adding files to watch in the .remote-sync.json file, it's working for me.
But im still missing the context menu.

**Comment by vincenzo-antolini-os** [comment]
Same here. Atom 1.17.0 Windows.

**Comment by jfkz** [comment]
Solution is here: https://github.com/yongkangchen/remote-sync/issues/388#issuecomment-302121984

**Comment by zaramme** [comment]
The Problem on this issue is not solved, isn't it?
I think It's not problem on the context menu, but Library loading.
On my Atom, Nothing occurred when I selected remote-sync context menu, 
and No Command Appears when I typed "remote sync" on Command Palettes.

**Comment by daverickdunn** [comment]
The missing context menu has been patched and is working with Atom 1.21 and Atom IDE (1.22...?): https://github.com/yongkangchen/remote-sync/commit/3432d5287fa035dea822e7a7599bab62454cdf69
