### ISSUE TITLE
Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

### ISSUE THREAD

**Issue by jatch** [yongkangchen/remote-sync#434]
remote-sync 4.1.5

fsevents@1.1.1 – Cannot find module '/Users/username/.atom/packages/remote-sync/node_modules/fsevents/lib/binding/Release/electron-v1.6-darwin-x64/fse.node'
binding@1.1.1 – Cannot find module '/Users/username/.atom/packages/remote-sync/node_modules/fsevents/lib/binding'
binding@1.1.1 – Cannot find module '/Users/username/.atom/packages/remote-sync/node_modules/fsevents/lib/binding'
binding@1.1.1 – Cannot find module '/Users/username/.atom/packages/remote-sync/node_modules/fsevents/lib/binding'
binding@1.1.1 – Cannot find module '/Users/username/.atom/packages/remote-sync/node_modules/fsevents/lib/binding'
binding@1.1.1 – Cannot find module '/Users/username/.atom/packages/remote-sync/node_modules/fsevents/lib/binding'

**Comment by zenbro** [comment]
You can rebuild outdated packages directly from atom: click on red bug icon in footer and press "Rebuild". This helped me after upgrading atom to 1.19.

**Comment by daverickdunn** [comment]
As @zenbro mentioned, a rebuild or reinstall should fix this. It's not a remote-sync specific issue.
