### ISSUE TITLE
doesn't work in 1.19.1

### ISSUE THREAD

**Issue by w-barath** [yongkangchen/remote-sync#435]
to reproduce:

install atom 1.19.1

$ rm -rf ~/.atom; # start fresh
$ atom

Navigate to Edit->Preferences
Click Install
Enter "sync"
Click "install" for remote-sync
open a project folder
right click on any folder in the project.... no sync options
exit atom
restart atom
open a project folder
right click... no sync options.

**Comment by DonRichards** [comment]
+1

**Comment by jeffatwanderlust** [comment]
+1

**Comment by developer99** [comment]
+1

**Comment by DonRichards** [comment]
Anyone working on this?

**Comment by developer99** [comment]
After upgrading to 1.19.1 and between making the changes in #388 and rebuilding outdated packages (click on red bug icon in footer and press "Rebuild").  It seemed to mostly work.

After setting up the config and setting a file to monitor, I had to restart Atom for it to work.  Also if you change any of the monitoring settings, it seems you have to restart to make it work.

**Comment by DonRichards** [comment]
Yes, I get this message but it comes up every time I reload atom. 

__Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.__

```terminal
remote-sync 4.1.5

binding@unknown – Cannot find module '/Users/don/.atom/packages/remote-sync/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/don/.atom/packages/remote-sync/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/don/.atom/packages/remote-sync/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/don/.atom/packages/remote-sync/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/don/.atom/packages/remote-sync/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/don/.atom/packages/remote-sync/node_modules/fsevents/lib/binding'
```

**Comment by DonRichards** [comment]
I think this issue has been seen before. [Solution](https://github.com/yongkangchen/remote-sync/issues/388#issuecomment-302121984)

**Comment by daverogers** [comment]
Some saint forked this project and made a new plugin, applying fixes the community had been submitting. Confirmed that it works with 1.19.x.

https://github.com/laymance/remote-sync-pro

**Comment by jogravila** [comment]
Hi, I have the same messages

remote-sync-pro 5.1.1

binding@unknown – Cannot find module '/Users/jordi/.atom/packages/remote-sync-pro/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/jordi/.atom/packages/remote-sync-pro/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/jordi/.atom/packages/remote-sync-pro/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/jordi/.atom/packages/remote-sync-pro/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/jordi/.atom/packages/remote-sync-pro/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/jordi/.atom/packages/remote-sync-pro/node_modules/fsevents/lib/binding'

**Comment by jogravila** [comment]
Sorry, resolved rebuildind pakage

**Comment by zeaaa** [comment]
+

**Comment by w-barath** [comment]
ty
